# name: Auto merge `dev` to `staging`

# on:
#   push:
#     branches:
#       - dev

# jobs:
#   merge:
#     runs-on: ubuntu-latest

#     steps:
#       - uses: actions/checkout@master

#       - uses: devmasx/merge-branch@master
#         with:
#           type: now
#           from_branch: dev
#           target_branch: staging
#           github_token: ${{ secrets.GITHUB_TOKEN }}

# permissions:
#   contents: write
